prompt --application/deployment/install/install_barcode
begin
--   Manifest
--     INSTALL: INSTALL-BARCODE
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.10.07'
,p_release=>'22.2.4'
,p_default_workspace_id=>7870050665145974
,p_default_application_id=>111
,p_default_id_offset=>0
,p_default_owner=>'JURKLEIN'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(32413510183890463)
,p_install_id=>wwv_flow_imp.id(32413038148876047)
,p_name=>'BARCODE'
,p_sequence=>10
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'CREATE TABLE "BARCODE" ',
'   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOT NULL ENABLE, ',
'	"CODE" VARCHAR2(20 CHAR), ',
'	 CONSTRAINT "BARCODE_ID_PK" PRIMARY KEY ("ID")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
''))
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(32413659032890466)
,p_script_id=>wwv_flow_imp.id(32413510183890463)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'BARCODE'
,p_last_updated_by=>'JURKLEIN_ADMIN'
,p_last_updated_on=>to_date('20230308144522','YYYYMMDDHH24MISS')
,p_created_by=>'JURKLEIN_ADMIN'
,p_created_on=>to_date('20230308144522','YYYYMMDDHH24MISS')
);
wwv_flow_imp.component_end;
end;
/
